name: Build with PyInstaller

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller NeoRealmBuilder.spec --clean

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: NeoRealmBuilder
        path: dist/NeoRealmBuilder.exe